### This file contain example requests how to use the app

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123",
    "passwordAgain": "test123",
    "username": "test",
    "fullName":"Okan Yeşiloğlu"
}

### Login with mail

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "okan1@gmail.com",
    "password": "deneme123"
}


### Login with username

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username": "test",
    "password": "test123"
}

###

GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjExLCJpYXQiOjE2NjIxOTk5MzZ9.5JANM7kILfH7CSOpH7YNMvClCQhEyaISiYLxPT0qpmE

### Binance test

GET http://localhost:3000


### Binance services Test

POST http://localhost:3000/watcher/get  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjExLCJpYXQiOjE2NjIyMDIzNTR9.A5ThnLRaqDDDPnkSFEYgyqC7knX2S9HqIxWZn2a8rEE
Content-Type: application/json

{
    "fromCrypto": "ADA",
    "toCrypto": "USDT"
}